---

name: Job Execution with Follow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # run manually

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # important!
    env:
      CI_DOMAIN: '<YOUR-DOMAIN>'
      CI_JOB: '<YOUR-JOB-NAME>'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: sudo apt install curl jq
        shell: bash

      - name: Starting and Following Job until it finished
        run: bash execute-and-follow-job.sh
        shell: bash
        env:
          CI_API_URL: "https://${{ env.CI_DOMAIN }}/api/job/${{ env.CI_JOB }}"
          CI_TOKEN: "${{ secrets.CI_TOKEN_RW }}"
          LOG_FILE: '/tmp/job.log'

      - uses: actions/upload-artifact@v4
        with:
          name: job-logs
          path: /tmp/job.log
          retention-days: 14
