---

name: Job Execution

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # run manually

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      CI_DOMAIN: '<YOUR-DOMAIN>'
      CI_JOB: '<YOUR-JOB-NAME>'
      CI_TOKEN_RO: '<YOUR-READ-ONLY-TOKEN-HERE>'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: sudo apt install curl
        shell: bash

      - name: Starting Job
        run: curl -XPOST https://${{ env.CI_DOMAIN }}/api/job/${{ env.CI_JOB }}?token=${{ secrets.CI_TOKEN_RW }} 2>/dev/null
        shell: bash

      - name: You can pull the current logs at this URL
        run: >
          echo "You can pull the current logs at this URL:"
          echo " > https://${{ env.CI_DOMAIN }}/api/job/${{ env.CI_JOB }}/tail?token=${{ env.CI_TOKEN_RO }}"
