---

name: Job Status

on:
  schedule:
    - cron: "25 6 * * *"
  workflow_dispatch:  # run manually

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      CI_DOMAIN: '<YOUR-DOMAIN>'
      CI_JOB: '<YOUR-JOB-NAME>'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: sudo apt install curl jq
        shell: bash

      - name: Pulling logs
        run: curl -f https://${{ env.CI_DOMAIN }}/api/job/${{ env.CI_JOB }}/logs?token=${{ secrets.CI_TOKEN_RW }} 2>/dev/null | jq > /tmp/job.log
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: job-logs
          path: /tmp/job.log
          retention-days: 14

      - name: Checking job-state
        run: curl -f https://${{ env.CI_DOMAIN }}/api/job/${{ env.CI_JOB }}/state?token=${{ secrets.CI_TOKEN_RW }} 2>/dev/null | jq -r '.state' | grep -q 'failed' && exit 1 || exit 0
        shell: bash
